src/account/urls.py
from django.urls import path
from account import views


app_name = 'account'

urlpatterns = [
    # path('my-profile/<int:pk>/', views.MyProfile.as_view(), name='my_profile'),
    path('my-profile/', views.MyProfile.as_view(), name='my_profile'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
    path('avatar/create/', views.CreateUserAvatar.as_view(), name='avatar-create'),
    path('activate/<str:username>/', views.ActivateUser.as_view(), name='activate'),
    path('avatars/list/', views.Avatars.as_view(), name='avatars'),
]

src/currency/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

API_PREFIX = 'api/v1'

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('', TemplateView.as_view(template_name='index.html'), name='index'),

                  path('account/', include('account.urls')),
                  path('rate/', include('rate.urls')),

                  # API
                  path(f'{API_PREFIX}/rates/', include('rate.api.urls')),

                  path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

                  re_path(rf'^{API_PREFIX}/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0),
                          name='schema-json'),
                  re_path(rf'^{API_PREFIX}/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  re_path(rf'^{API_PREFIX}/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

src/rate/urls.py
from django.urls import path
from rate import views

from django.views.decorators.cache import cache_page

app_name = 'rate'

urlpatterns = [
    path('list/', cache_page(60)(views.RateListView.as_view()), name='list'),
    # path('list/', views.RateListView.as_view(), name='list'),
    path('list/lastest/', views.LatestRates.as_view(), name='list-latest'),
    path('list/csv/', views.CSVView.as_view(), name='list-csv'),

    path('contact-us/create/', views.CreateContactUsView.as_view(), name='contact-us-create'),
]

src/templates/parts/navbar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">
                Index {{ HELLO }}
            </a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'rate:list' %}">
                Rate List
            </a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'rate:list-latest' %}">
                Latest Rates
            </a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'rate:contact-us-create' %}">
                Contact Us
            </a>
        </li>

        {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:my_profile' %}">
                    My Profile
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:avatar-create' %}">
                    Upload Avatar
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:avatars' %}">
                    Avatars
                </a>
            </li>
        {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:sign-up' %}">
                    Sign Up
                </a>
            </li>
        {% endif %}

    </ul>
</nav>

src/templates/parts/pagination.html
<div class="pagination">

                <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&{{ GET_PARAMS }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&{{ GET_PARAMS }}">previous</a>
        {% endif %}

                    <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}&{{ GET_PARAMS }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}&{{ GET_PARAMS }}">last &raquo;</a>
                    {% endif %}
    </span>

    <form>
        <input name="page" type="number" min="1" value="{{ page_obj.number }}">
        {% for key, value in request.GET.items %}
            {% if key != 'page' %}
                <input type="hidden" name="{{ key }}" value="{{ value }}">
            {% endif %}
        {% endfor %}
        <button type="submit">Go to page</button>
    </form>


</div>