src/currency/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

API_PREFIX = 'api/v1'

urlpatterns = [
                  path('admin/', admin.site.urls),

                  path('', TemplateView.as_view(template_name='index.html'), name='index'),

                  path('account/', include('account.urls')),
                  path('rate/', include('rate.urls')),

                  # API
                  path(f'{API_PREFIX}/rates/', include('rate.api.urls')),

                  path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

                  re_path(rf'^{API_PREFIX}/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0),
                          name='schema-json'),
                  re_path(rf'^{API_PREFIX}/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  re_path(rf'^{API_PREFIX}/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

src/rate/api/urls.py
from django.urls import path

from . import views

from rest_framework.routers import DefaultRouter

app_name = 'api-rate'

router = DefaultRouter()
router.register('rates', views.RateAPIViewSet, basename='rate')

urlpatterns = [
    path('latest/', views.LatestRatesApiView.as_view(), name='latest-rates'),
]

urlpatterns.extend(router.urls)

src/rate/urls.py
from django.urls import path
from rate import views

from django.views.decorators.cache import cache_page

app_name = 'rate'

urlpatterns = [
    path('list/', cache_page(60)(views.RateListView.as_view()), name='list'),
    # path('list/', views.RateListView.as_view(), name='list'),
    path('list/lastest/', views.LatestRates.as_view(), name='list-latest'),
    path('list/csv/', views.CSVView.as_view(), name='list-csv'),

    path('contact-us/create/', views.CreateContactUsView.as_view(), name='contact-us-create'),
]

src/rate/models.py
from django.db import models
from rate import choices
from django.core.cache import cache



class Rate(models.Model):
    currency = models.PositiveSmallIntegerField(choices=choices.CURRENCY_CHOICES, db_index=True)
    source = models.PositiveSmallIntegerField(choices=choices.SOURCE_CHOICES)
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sale = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        index_together = (
            ('currency', 'source'),
        )

        permissions = [
            ("full_edit", "This permission allows user to update all available fields in Rate model"),
        ]

    # def __str__(self):
    # TODO FK
    #     return f'{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        key = self.__class__.cache_key()
        cache.delete(key)

    @classmethod
    def cache_key(cls) -> str:
        import hashlib
        return hashlib\
            .md5(f"RateLatestKey".encode())\
            .hexdigest()


class ContactUs(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=128)
    message = models.TextField()

src/rate/api/views.py
from rest_framework import viewsets, generics
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from rate.api.serializers import RateSerializer
from rate.models import Rate
from rate.selectors import get_latest_rates


class RateAPIViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().order_by('-id')
    serializer_class = RateSerializer


class LatestRatesApiView(generics.GenericAPIView):
    permission_classes = (AllowAny, )
    authentication_classes = ()

    def get(self, request):
        rates = get_latest_rates()
        serializer = RateSerializer(rates, many=True)
        return Response(serializer.data)

src/rate/views.py
import csv
from django.http import HttpResponse
from django.shortcuts import render

from django.views.generic import ListView, CreateView
from rate.models import Rate, ContactUs
from django.urls import reverse_lazy
from django.views.generic import View
from rate import choices
from rate.selectors import get_latest_rates
from rate.filters import RateFilter

from rate.utils import display

from django_filters.views import FilterView


class RateListView(FilterView):
    queryset = Rate.objects.all()
    paginate_by = 10
    filterset_class = RateFilter
    template_name = 'rate/rate_list.html'

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['GET_PARAMS'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        context['object_count'] = context['object_list'].count()
        return context


class CreateContactUsView(CreateView):
    success_url = reverse_lazy('index')
    model = ContactUs
    fields = ('email', 'subject', 'message')

    def form_valid(self, form):
        # TODO send message
        return super().form_valid(form)


class CSVView(View):
    headers = [
        'sale', 'buy',
        'source', 'currency',
    ]

    def get(self, request):
        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'
        writer = csv.writer(response)

        from time import sleep

        sleep(15)

        writer.writerow(self.headers)

        for rate in Rate.objects.all().iterator():
            writer.writerow(
                [display(rate, header)
                 for header in self.__class__.headers]
            )

        return response


class LatestRates(View):
    def get(self, request):
        context = {'rate_list': get_latest_rates()}
        print(context)
        return render(request, 'rate/latest-rates.html', context=context)

src/rate/templates/rate/contactus_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <form action="{% url 'rate:contact-us-create' %}"
                  method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Send</button>
            </form>
        </div>
    </div>
{% endblock content %}

src/rate/templates/rate/latest-rates.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <button id="update-rates-js">Update</button>
        <div class="col latest-rates-row-js">
            {% for rate in rate_list %}
                <p>
                    COUNTER: {{ forloop.counter }}
                    ID: {{ rate.id }}
                    Buy: {{ rate.buy }}
                    Currency: {{ rate.get_currency_display }}
                    Source: {{ rate.get_source_display }}
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
    <script>
        $(document).ready(function () {
            $("#update-rates-js").click(function () {
                $.get('/api/v1/rates/latest/').done(
                    function (data, status) {

                        let ratesSelector = $('.latest-rates-row-js');

                        ratesSelector.empty();

                        var i;
                        for (i = 0; i < data.length; i++) {
                            ratesSelector.append(
                                `<p>ID: ${data[i].id} Buy: ${data[i].buy} Sale: ${data[i].sale}</p>`
                            );
                        }
                    }
                );
            });
        });
    </script>
{% endblock extra_js %}

src/rate/templates/rate/rate_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <div>{{ object_list.count }}</div>
            <div>{{ object_count }}</div>
            <div><a href="{% url 'rate:list-csv' %}">Download CSV</a></div>

            {#     TODO move to parts/filters.html       #}
            <form method="get">
                {{ filter.form.as_p }}
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
            </form>

            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Buy</th>
                    <th>Sale</th>
                    <th>Source</th>
                    <th>Currency</th>
                    <th>Created</th>
                </tr>
                {% for rate in rate_list %}
                    <tr>
                        <td>{{ rate.id }}</td>
                        <td>{{ rate.buy }}</td>
                        <td>{{ rate.sale }}</td>
                        <td>{{ rate.get_source_display }}</td>
                        <td>{{ rate.get_currency_display }}</td>
                        <td>{{ rate.created.date }}</td>
                    </tr>
                {% endfor %}
            </table>

            {% include 'parts/pagination.html' %}
        </div>
    </div>
{% endblock content %}